# Домашнее задание 2 (5 баллов).

Все задания ниже имеют равный вес (5/16).

In [2]:
import pandas as pd

#### Описание данных

В папке Dat (https://github.com/hse-ds/iad-intro-ds/blob/master/2023/homeworks/Data.zip) находится информация о студентах. Всего 10 групп студентов. Файлы делятся на две категории:
    * Students_info_i - информация о студентах из группы i
    * Students_marks_i - оценки студентов из группы i за экзамены

### Одно из важных достоинств pandas $-$ это удобные методы реляционного взаимодействия с данными, аналогичные, например, возможностям SQL для слияния и конкатенации таблиц: merge, join, concat. Наличие готовых методов позволяет не реализовывать самостоятельно поэлементную обработку данных и оперировать сразу целыми таблицами данных.

Подробно об этих методах посмотрите тут: https://www.kaggle.com/residentmario/renaming-and-combining#Combining

#### Задание 1. Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.¶

In [3]:
df_0 = pd.read_csv('Students_info_0.csv')
df_1 = pd.read_csv('Students_info_1.csv')
df_2 = pd.read_csv('Students_info_2.csv')
df_3 = pd.read_csv('Students_info_3.csv')
df_4 = pd.read_csv('Students_info_4.csv')
df_5 = pd.read_csv('Students_info_5.csv')
df_6 = pd.read_csv('Students_info_6.csv')
df_7 = pd.read_csv('Students_info_7.csv')
df_8 = pd.read_csv('Students_info_8.csv')
df_9 = pd.read_csv('Students_info_9.csv')
df_students = pd.concat([df_0, df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_8, df_9])

df_marks_0 = pd.read_csv('Students_marks_0.csv')
df_marks_1 = pd.read_csv('Students_marks_1.csv')
df_marks_2 = pd.read_csv('Students_marks_2.csv')
df_marks_3 = pd.read_csv('Students_marks_3.csv')
df_marks_4 = pd.read_csv('Students_marks_4.csv')
df_marks_5 = pd.read_csv('Students_marks_5.csv')
df_marks_6 = pd.read_csv('Students_marks_6.csv')
df_marks_7 = pd.read_csv('Students_marks_7.csv')
df_marks_8 = pd.read_csv('Students_marks_8.csv')
df_marks_9 = pd.read_csv('Students_marks_9.csv')

df_marks = pd.concat([df_marks_0, df_marks_1, df_marks_3, df_marks_4, df_marks_5, df_marks_6, df_marks_7, df_marks_8, df_marks_9])

df = pd.merge(df_students, df_marks, on = 'index', how ='left')
df.head()

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72.0,72.0,74.0
1,1,female,group C,some college,standard,completed,group1,69.0,90.0,88.0
2,2,female,group B,master's degree,standard,none,group1,90.0,95.0,93.0
3,3,male,group A,associate's degree,free/reduced,none,group1,47.0,57.0,44.0
4,4,male,group C,some college,standard,none,group1,76.0,78.0,75.0

In [4]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

#### Задание 2. Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [5]:
df = df.drop('index', axis = 1)
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72.0,72.0,74.0
1,female,group C,some college,standard,completed,group1,69.0,90.0,88.0
2,female,group B,master's degree,standard,none,group1,90.0,95.0,93.0
3,male,group A,associate's degree,free/reduced,none,group1,47.0,57.0,44.0
4,male,group C,some college,standard,none,group1,76.0,78.0,75.0

#### Задание 3. Выведите на экран размеры полученной таблицы

In [6]:
print(df.shape)

(1000, 9)

#### Задание 4. Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [7]:
stat = df.describe()
stat = stat.drop('count', axis = 0)
stat = stat.drop('25%', axis = 0)
stat = stat.drop('50%', axis = 0)
stat = stat.drop('75%', axis = 0)
stat

      math score  reading score  writing score
mean   65.847778      69.133333      68.024444
std    15.226731      14.636949      15.329001
min     0.000000      17.000000      10.000000
max   100.000000     100.000000     100.000000

#### Задание 5. Проверьте, есть ли в таблице пропущенные значения

In [8]:
print(f'Here {df.isnull().sum().sum()} such values')

Here 300 such values

#### Задание 6. Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [9]:
stat.iloc[[0]]

      math score  reading score  writing score
mean   65.847778      69.133333      68.024444

**Задание 7. Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.**

In [10]:
print('               completed')
print()
stat1 = df[df['test preparation course'] == 'completed'].describe()
print(stat1.iloc[[1]])
print()
print()
print('                  none')
print()
stat2 = df[df['test preparation course'] == 'none'].describe()
print(stat2.iloc[[1]])

               completed

      math score  reading score  writing score
mean   69.547988      73.934985      74.427245


                  none

      math score  reading score  writing score
mean    63.77643      66.445407      64.440208

**Задание 8. Выведите на экран все различные значения из столбца lunch.**

In [11]:
print(df['lunch'].unique())

['standard' 'free/reduced']

**Задание 9. Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [12]:
df.rename(columns = {'parental level of education': 'education', 'test preparation course': 'test preparation'}, inplace = True)
df.head()

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72.0,72.0,74.0
1,female,group C,some college,standard,completed,group1,69.0,90.0,88.0
2,female,group B,master's degree,standard,none,group1,90.0,95.0,93.0
3,male,group A,associate's degree,free/reduced,none,group1,47.0,57.0,44.0
4,male,group C,some college,standard,none,group1,76.0,78.0,75.0

**Зафиксируем минимальный балл для сдачи экзамена**

In [13]:
passmark = 50
df[df['math score'] >= passmark].count()[0]

777

**Задание 10. Ответьте на вопросы:**
    * Какая доля студентов сдала экзамен по математике (passmark >= 50)?
    * Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
    * Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [14]:
print('Какая доля студентов сдала экзамен по математике (passmark >= 50)?')
print('Answer:')
print(df[df['math score'] >= passmark].count()[0] / df.count()[0])
print()
print('Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике? ')
print('Answer:')
print(df.loc[(df['math score'] >= passmark) & (df['test preparation'] == 'completed')].count()[0] / df[df['test preparation'] == 'completed'].count()[0])
print()
print('Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?')
print('Answer:')
print(df.loc[(df['math score'] < passmark) & (df['gender'] == 'female') ].count()[0] / df.loc[(df['gender'] == 'female') & (df['test preparation'] == 'none')].count()[0])
print()

Какая доля студентов сдала экзамен по математике (passmark >= 50)?
Answer:
0.777

Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
Answer:
0.8324022346368715

Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?
Answer:
0.23952095808383234

**Задание 11. С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**
    * Для каждой этнической группы выведите средний балл за экзамен по чтению
    * Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [15]:
%%time
print('Для каждой этнической группы выведите средний балл за экзамен по чтению')
print()
print(df.groupby(by = 'race/ethnicity')['reading score'].mean())

Для каждой этнической группы выведите средний балл за экзамен по чтению

race/ethnicity
group A    65.046512
group B    66.905325
group C    69.301038
group D    70.167382
group E    72.699187
Name: reading score, dtype: float64
CPU times: user 5.33 ms, sys: 0 ns, total: 5.33 ms
Wall time: 18.5 ms

In [16]:
%%time
print('Для каждого уровня образования выведите минимальный балл за экзамен по письму')
print()
print(df.groupby(by = 'education')['writing score'].min())

Для каждого уровня образования выведите минимальный балл за экзамен по письму

education
associate's degree    35.0
bachelor's degree     38.0
high school           15.0
master's degree       46.0
some college          19.0
some high school      10.0
Name: writing score, dtype: float64
CPU times: user 3.93 ms, sys: 991 µs, total: 4.92 ms
Wall time: 7.36 ms

**Задание 12. Выполните задание 11 с помощью циклов. Сравните время выполнения.**

In [17]:
%%time
ans_ad = 100
ans_bd = 100
ans_hs = 100
ans_md = 100
ans_sc = 100
ans_shs = 100


for i in range(len(df)):
    if df['education'][i] == "associate's degree" and not pd.isna(df['writing score'][i]) and df['writing score'][i] < ans_ad:
        ans_ad = df['writing score'][i]
    elif df['education'][i] == "bachelor's degree" and not pd.isna(df['writing score'][i]) and df['writing score'][i] < ans_bd:
        ans_bd = df['writing score'][i]
    elif df['education'][i] == "high school" and not pd.isna(df['writing score'][i]) and df['writing score'][i] < ans_hs:
        ans_hs = df['writing score'][i]
    elif df['education'][i] == "master's degree" and not pd.isna(df['writing score'][i]) and df['writing score'][i] < ans_md:
        ans_md = df['writing score'][i]
    elif df['education'][i] == "some college" and not pd.isna(df['writing score'][i]) and df['writing score'][i] < ans_sc:
        ans_sc = df['writing score'][i]
    elif df['education'][i] == "some high school" and not pd.isna(df['writing score'][i]) and df['writing score'][i] < ans_shs:
        ans_shs = df['writing score'][i]

print("associate's degree", ans_ad)
print("bachelor's degree", ans_bd)
print("high school", ans_hs)
print("master's degree", ans_md)
print("some college", ans_sc)
print("some high school", ans_shs)

associate's degree 35.0
bachelor's degree 38.0
high school 15.0
master's degree 46.0
some college 19.0
some high school 10.0
CPU times: user 63 ms, sys: 0 ns, total: 63 ms
Wall time: 66.3 ms

In [18]:
df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72.0,72.0,74.0
1,female,group C,some college,standard,completed,group1,69.0,90.0,88.0
2,female,group B,master's degree,standard,none,group1,90.0,95.0,93.0
3,male,group A,associate's degree,free/reduced,none,group1,47.0,57.0,44.0
4,male,group C,some college,standard,none,group1,76.0,78.0,75.0
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88.0,99.0,95.0
996,male,group C,high school,free/reduced,none,group10,62.0,55.0,55.0
997,female,group C,high school,free/reduced,completed,group10,59.0,71.0,65.0
998,female,group D,some college,standard,completed,group10,68.0,78.0,77.0
999,female,group D,some college,free/reduced,none,group10,77.0,86.0,86.0

**Задание 13. Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.**

Это можно сделать с помощью сводных таблиц (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

In [19]:
grouped = df.pivot_table(index=['gender', 'education'], values = ['math score', 'reading score', 'writing score'])
grouped

                           math score  reading score  writing score
gender education
female associate's degree   65.238532      74.082569      73.834862
       bachelor's degree    68.241379      77.120690      78.137931
       high school          59.305882      68.529412      66.694118
       master's degree      67.176471      77.294118      78.235294
       some college         64.971963      73.214953      73.869159
       some high school     59.207317      68.926829      68.036585
male   associate's degree   69.681319      66.494505      64.538462
       bachelor's degree    69.604167      67.979167      67.520833
       high school          64.688889      61.077778      58.144444
       master's degree      74.590909      72.818182      72.636364
       some college         69.450000      65.700000      63.950000
       some high school     67.189189      64.189189      60.675676

#### Задание 14. Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [30]:
arr = []
arr1 = []
arr2 = []
for i in df['math score']:
  if i >= passmark:
    arr.append('P')
  else:
    arr.append('F')
df['Math_PassStatus'] = arr
for i in df['reading score']:
  if i >= passmark:
    arr1.append('P')
  else:
    arr1.append('F')
df['Reading_PassStatus'] = arr1
for i in df['writing score']:
  if i >= passmark:
    arr2.append('P')
  else:
    arr2.append('F')
df['Writing_PassStatus'] = arr2
df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72.0,72.0,74.0,P,P,P
1,female,group C,some college,standard,completed,group1,69.0,90.0,88.0,P,P,P
2,female,group B,master's degree,standard,none,group1,90.0,95.0,93.0,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47.0,57.0,44.0,F,P,F
4,male,group C,some college,standard,none,group1,76.0,78.0,75.0,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88.0,99.0,95.0,P,P,P
996,male,group C,high school,free/reduced,none,group10,62.0,55.0,55.0,P,P,P
997,female,group C,high school,free/reduced,completed,group10,59.0,71.0,65.0,P,P,P
998,female,group D,some college,standard,completed,group10,68.0,78.0,77.0,P,P,P
999,female,group D,some college,free/reduced,none,group10,77.0,86.0,86.0,P,P,P

#### Задание 15. Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [31]:
arr3 = []
for i in range(len(arr)):
  if arr[i] == 'F' or arr1[i] == 'F' or arr2[i] == 'F':
    arr3.append('F')
  else:
    arr3.append('P')

df['OverAll_PassStatus'] = arr3
df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72.0,72.0,74.0,P,P,P,P
1,female,group C,some college,standard,completed,group1,69.0,90.0,88.0,P,P,P,P
2,female,group B,master's degree,standard,none,group1,90.0,95.0,93.0,P,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47.0,57.0,44.0,F,P,F,F
4,male,group C,some college,standard,none,group1,76.0,78.0,75.0,P,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88.0,99.0,95.0,P,P,P,P
996,male,group C,high school,free/reduced,none,group10,62.0,55.0,55.0,P,P,P,P
997,female,group C,high school,free/reduced,completed,group10,59.0,71.0,65.0,P,P,P,P
998,female,group D,some college,standard,completed,group10,68.0,78.0,77.0,P,P,P,P
999,female,group D,some college,free/reduced,none,group10,77.0,86.0,86.0,P,P,P,P

#### Задание 16. Переведем баллы в оценки

### Система перевода баллов в оценки
####    больше 90 = A
####      80-90 = B
####      70-80 = C
####      60-70 = D
####      50-60 = E
####    меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

**В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).**

In [42]:
def GetGrade(average_mark):
    if average_mark > 90:
      return 'A'
    if average_mark > 80:
      return 'B'
    if average_mark > 70:
      return 'C'
    if average_mark > 60:
      return 'D'
    if average_mark > 50:
      return 'E'
    return 'F'

avg = (df['math score'] + df['reading score'] + df['writing score'])/3
df['Grade'] = avg.map(GetGrade)
df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Reading_PassStatus,Writing_PassStatus,OverAll_PassStatus,Grade
0,female,group B,bachelor's degree,standard,none,group1,72.0,72.0,74.0,P,P,P,P,C
1,female,group C,some college,standard,completed,group1,69.0,90.0,88.0,P,P,P,P,B
2,female,group B,master's degree,standard,none,group1,90.0,95.0,93.0,P,P,P,P,A
3,male,group A,associate's degree,free/reduced,none,group1,47.0,57.0,44.0,F,P,F,F,F
4,male,group C,some college,standard,none,group1,76.0,78.0,75.0,P,P,P,P,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88.0,99.0,95.0,P,P,P,P,A
996,male,group C,high school,free/reduced,none,group10,62.0,55.0,55.0,P,P,P,P,E
997,female,group C,high school,free/reduced,completed,group10,59.0,71.0,65.0,P,P,P,P,D
998,female,group D,some college,standard,completed,group10,68.0,78.0,77.0,P,P,P,P,C
999,female,group D,some college,free/reduced,none,group10,77.0,86.0,86.0,P,P,P,P,B